commitizen:
  name: cz_customize
  tag_format: $version
  version: 0.0.1
  customize:
    message_template: "{{change_type}}: {{message}}"
    example: "feature: this feature enable customize through config file"
    schema: "<type>: <body>"
    questions:
      - type: "list"
        name: "change_type"
        choices:
          ["✨ feat", "🐞 fix", "📃 docs", "⚙ ci️", "🧪 test", "🪄 refactor"]
        message: "Select the type of change you are committing"
      - type: "input"
        name: "message"
        message: "Short description of the commit"
